# General Configutaions
run_label: 'smdl'
gpu_ids: '0'
seed: 99                            # '0' means no manual seeding

# Incremental Learning Configurations
repeat_rounds: 1

# Dataset Configurations
dataset:
    name: 'CIFAR'
    total_num_classes: 100

# Training Configurations
epochs: 30

batch_size: 2
batch_size_test: 100

learning_rate: 0.1
momentum: 0.9
weight_decay: 0.0001

use_submobular_batch_selection: True