# General Configutaions
run_label: 'smile'
gpu_ids: '6'
seed: 99

# Incremental Learning Configurations
repeat_rounds: 1
class_per_episode: 20

# Training Configurations
epochs: 100

batch_size: 512
batch_size_test: 100

learning_rate: 0.1
momentum: 0.9
weight_decay: 0.0001

# Dataset Configurations
dataset:
    name: 'CIFAR'
    total_num_classes: 100
    memory_budget: 2000   # Upper limit on the number of images that can be retained as exemplars