# General Configutaions
run_label: 'smile'
gpu_ids: '6'
seed: 0                            # '0' means no manual seeding

# Incremental Learning Configurations
repeat_rounds: 3
class_per_episode: 20
use_all_exemplars: False           # All the available images from each class will be used in each episode, if set to True.
                                   # 'memory_budget' will be ignored.
sampling_strategy: 'submodular'    # Can be either: 'random', 'submodular'
load_class_list_from_file: True    # Expects the class list for each of the 'rounds' as a pickle file in '/outputs' folder.

# Dataset Configurations
dataset:
    name: 'CIFAR'
    total_num_classes: 100
    memory_budget: 2000            # Upper limit on the number of images that can be retained as exemplars

# Training Configurations
epochs: 100

batch_size: 512
batch_size_test: 100

learning_rate: 0.1
momentum: 0.9
weight_decay: 0.0001