# Configuration File

run_label: 'smile'
gpu_ids: '7'

seed: 99

repeat_rounds: 1
class_per_episode: 50

epochs: 100

batch_size: 512
batch_size_test: 100

learning_rate: 0.1
momentum: 0.9
weight_decay: 0.0001
